### ISSUE TITLE
Delete confirming popup does not seem to be working on test site

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#103]
It doesn't seem that the delete confirmation pop-up is working on the following pages:
Categories, Items, Recipes

Confirmation is only seen when deleting a user on the Users page. Perhaps the test site was not fully updated with the new change or perhaps this is a bug. Please check.

**Comment by swash99** [comment]
The delete confirmation was not implimented on these pages before. Added the confirmation for categories and recipes. Have not added confirmation for items since the design already requires the users to confirm the deletion of selected items.
