### ISSUE TITLE
Session timeout improvements

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#104]
I tried out the session timeout value setting under Account tab and ran into a bunch of issues. Suggested improvements related to that:
1. Visually the account page settings are getting a bit squished together and with new features added over time, some of the layout has lost context. Example:  Within the block with the bold "Edit Credentials" title you can also set the timezone and now the session timeout value. Things should be separated a bit so each setting type stands out individually.
2. The session timeout field has bunch of issues:

i. There is no unit mentioned for the value. Seconds, minutes, hours, days?

ii. The field should be set to accept only integer types. I can enter "abc" and click save, which seems to send the data to the backend and the value defaults to 0.

iii. An invalid session timeout value defaults to 0 and then after the user logs in and clicks anything, he is logged out. A timeout value of 0 essentially locks the user out of his account. This is bad.

iv. Personally I think a drop-down list with a pre-defined list of values might be more appropriate for the timeout field. There is no need to give the flexibility of entering any value. The listed session timeout values (in minutes) can be listed as:  15, 30, 60, 120, 150, 300. That should be good enough.

v. I'm locked out of my account because the session timeout is 0! Please change value in database :-)

**Comment by swash99** [comment]
Issue resolved in commit e341d15
