### ISSUE TITLE
Timezone not handling daylight savings time

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#106]
In a lot of western countries like Canada, daylight savings time will be used causing the time to be moved forward/behind by an hour.

Problem being seen:
- Timezone for user is set to America/Toronto
- Restaurant is open till 11 PM after which things are shut down and the inventory list created.
- At 11 PM, the website will change the date to the next day, an hour before it should actually be done i.e. 12 AM.

I think this issue is because daylight savings time is not being handled properly. Investigate possible solutions to this problem which can include but are not limited to:
1. Automatically figure out the current time and whether daylight savings is applicable to it or not. There must be some kind of library which handles this.
2. The last and not so user friendly way would be to add a "Enable/Disable Daylight Savings Time" toggle button next to timezone under Admin Tasks. The user would manually set this when time changes... i don't like this idea since it seems primitive, but it can be used as a last resort if needed.

**Comment by swash99** [comment]
Issue resolved in commit 187ac10
