### ISSUE TITLE
Print Preview:  Make notes field configurable

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#108]
The user can only see the "quantity required" values in the Print Preview page. This flow makes it a bit difficult to add any notes related to the calculated quantity required value and the user would have to go back to the main page, find the category and item, and then enter the note.

Investigate the possibility of making the "Notes" column in print preview page editable, so the note can be edited and saved right there before creating the PDF or messaging the inventory to another user.

**Comment by swash99** [comment]
Issue resolved in commit 7a34b65
