### ISSUE TITLE
Add verification of inventory based on actual sales

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#109]
Currently we generate an estimated amount required for an inventory item based on estimated sales for the next day. We want to expand this feature to include a check to see how accurate the users estimation numbers have been.

Feature flow:
- Add an "**Actual Sales**" field on the main category_status.php page. This will be filled out by the user before he starts entering current inventory quantity at the end of a business day. Place it wherever you think is reasonable.
- Based on the actual sales figure entered, generate estimated expected quantity present for each item. A new column called "**Expected Quantity**" (or something like that) can be added on the category_status.php page perhaps to the left of "**Quantity Present**" column and this is populated with the calculated estimated quantity present.

The calculation will be made using the numbers in the Admin Tasks -> Items page. For example:

**Under Admin Tasks-> Items**
Quantity for sales:  $2000
Chicken quantity (for $2000 sales):  100

**Values for next day (Monday) sales, entered/estimated on Sunday**
Estimated sales for Monday:  $3000
Estimated calculated chicken required for Monday: 150

**Values entered at end of business day on Monday**
Actual sales:  $2500
Estimated chicken that should be present:  150 - ($2500/$2000 \* 200) = 25
The estimated quantity present value of 25 should be populated in the new "**Estimated Quantity**" column.
- Another field should be added to Admin Tasks -> Items page called "**Acceptable Deviation %**" (or something like that). This is the acceptable +/- error or deviation range as a percentage between estimated quantity present and actual quantity present.
- When the user enters the actual quantity present in the main page, you will trigger a quick percentage deviation calculation using the following formula:  
  **< Actual quantity present > - < Estimated quantity present > \* 100 / < Actual quantity present >**  
  The sign from the subtraction is irrelevant and you can just take the absolute value of the subtraction. We only care about the magnitude, not negativity or positivity.
- If the percentage deviation is greater than the acceptable deviation specified in the Items page, then you will flag the user. The flagging process can be a simple process of a pop-up notification or if you want to apply your fancy skills you can add a small red exclamation mark next to the box where the quantity is outside acceptable deviation. Either way it might be good to have a more "persistent" mark like the red exclamation mark once any pop-up is dismissed.

Example:
Calculated estimated chicken that should be present:  25
Quantity present entered by user:  20
Deviation calculation:  (20 - 25) \* 100 / 20 = 25% (absolute number taken, negative sign ignored)
Trigger flag if:    deviation% > acceptable deviation%
If Acceptable Deviation is 10%:  25% > 10% == Trigger flag
If Acceptable Deviation is 24%:  25% > 24% == Trigger flag
If Acceptable Deviation is 25%:  25% > 25% == Do not Trigger flag
If Acceptable Deviation is 30%:  25% > 30% == Do not Trigger flag

**Comment by swash99** [comment]
Added an intial version for testing on the test site. 

A couple of points that I wanted to ask: 
- In the items table in items.php we have a rounding option that, if applicable, is applied to the "Quantity Required" in print preview. Should this option also be applied to the new "Expected Quantity" field in category_status.php.
- The "Expected Quantity" uses the "Expected Sales" value in its calculation but we had moved the "Expected Sales" input field to the print preview page. Should this field be moved back to category status page since its required there now. It may be tedious for a user to have to switch between pages just to adjust this field.

**Comment by sa31fh** [comment]
1
Very good question. I'm thinking that since we use "Expected Sales" to determine the quantity of an item to be consumed/required the next day, we should apply the same method to calculate the **expected quantity consumed** on a day given the **Actual Sales** for the day. If you take the chicken example in my original post above:

**Actual Sales**: $2500
**Estimated quantity which _should_ have been consumed**: ($2500/$2000 \* 200) = 25 [Apply rounding option to this calculated figure]
**Estimated quantity present**:  150 - 25 (or whatever the 25 will be converted to after rounding)

Think about it and see if that makes sense. I get the feeling this will be one of those things which will have to be used in the restaurant and the functionality determined accordingly!

2 
Ah you may be getting a little confused here. Remember that the "Expected Sales" figure in print preview is for the _next_ days sales. The "Expected Quantity" calculation will be using the expected sales figure set the _previous_ day. For example at the end of business on Tuesday, we should be using the expected sales figure set on Monday to determine the expected quantity which should be present.

Right now I believe the "Expected Sales" is just a single global variable. This feature will require you to create a table which keeps track of expected sales value set for each day! A simple table with a date and expected sales column should be sufficient for this.
