### ISSUE TITLE
Some rephrasing of headings

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#111]
All on category_status page:
"Actual Sales" --> "Todays Sales"
"Expected Quantity" --> "Expected Quantity Present"
"Quantity Present" --> "Actual Quantity Present"

If you want to be really fancy, I was thinking maybe a merged heading would look good (Expected and Actual are separated columns, with one merged Quantity Present above it):
`-----------------------`
`|        Quantity Present      |`
`-----------------------`
`| Expected     |     Actual      |`
`------------------------`

**Comment by swash99** [comment]
Iv changed the names but I haven't added the extra row yet nor added the word 'present'. If its aboslutely necessary then I'll add the row, if the current wording is not acceptable. Just trying to avoid messing with my beautiful symmetrical lines. 

The change is on the auntys site.

**Comment by sa31fh** [comment]
- The extra row was just my idea to minimize redundancy of the wording.
- We can keep the change you made for the time being. However I would still suggest you keep this in mind and if you can incorporate the fact that the two columns are for the quantity 'present', then that would be better. While I was walking them through the feature I got a billion questions thrown at me and I myself was confused as to what the columns exactly meant!

**Comment by swash99** [comment]
Issue resolved in commit 4c4af94
