### ISSUE TITLE
Send message to admins summarizing deviation warnings for the day

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#114]
This is a nice-to-have feature which might require a little research:
We want to send an internal message to all admins in the system at a reasonably late time (e.g. 3 AM) with a small summary of the items with deviation warnings generated on them for the day. Message can be as condensed as being reduced to item name, expected quantity present and actual quantity present.

The details like time of messaging and settings the receivers of the message can made customizable but lets get it working first. The main question is how to trigger an action at a preset time. Perhaps the database offers some interesting functionality to help here?

**Comment by swash99** [comment]
Added the feature in commit 80f33bb
