### ISSUE TITLE
Create buyer/seller invoice flow

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#138]
This issue is dependent on #137 

We want to create the following flow:
- User enters inventory.
- Clicking on print preview generates quantity required table along with associated cost.
- This invoice is then sent to another user in the back kitchen.
- User fills out quantity actually being delivered in the invoice return table and the new "delivered quantity" cost column is calculated.

A few points related to the flow above:
- Perhaps it may be useful to have a new 'Invoice' tab in the navbar
- The 'sending' of invoice to another user can happen in a few different ways. Either the user clicks a button like "Generate Invoice" in the print preview table and it saves the pending invoice. Or perhaps we have a messaging concept where one user 'sends' the invoice to the other user.
- Similarly with the concept of replying to the invoice a user can fill out the delivery sections and 'sign off' on the invoice which is then just saved. Or perhaps we want a messaging concept where the user "sends" the reply to invoice request back to the original sender.

As with a lot of features, things aren't set in stone. We should iron out the invoice flow so it fits into the rest of the product properly.

This feature will probably require a few iterations of making changes based on customer feedback and it will be in a semi-experimental state for some time. Given that its best we try to implement a beta version as soon as possible to get some time to deal with feedback.

**Comment by sa31fh** [comment]
I have a relatively simple idea for a first phase implementation of the invoice flow. We already have cost related columns implemented, so thats half the work done. 

The idea below is flexible and open to change as you see fit. There are no strict requirements:

1. Add an 'Invoice' tab in the bottom navbar.
2. Add a 'Track Invoice' button to Print Preview page.
3. On clicking 'Track Invoice' button we should start tracking this date in the invoice page.
4. The 'Invoice' button should navigate to a page where the left column has dates in reverse chronological order. On clicking a date, the right side of the page should be populated with a table similar to the print preview table but without the 'Quantity Present' column since that is not necessary.
5. A new column will be added in Invoice called 'Quantity Delivered'.
6. All columns should be read-only except Quantity Delivered and Notes.
7. Add a 'print preview'' button on this page too, which will generate a table with data which can be shared or saved as pdf.
8. A new column should be added to this new print preview invoice table which calculates cost based on Quantity Delivered.

Lets implement this as an initial step to get this feature working. We can refine things going on, but the underlying functionality is important.

**Comment by swash99** [comment]
Feature added in commit e71d28c
