### ISSUE TITLE
Display information to assist in sales prediction

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#142]
When the user is trying to determine a figure for the "Expected Sales" field on the print preview page, it can be a hassle to dig around for relevant historical sales figures needed for the purpose. We want to provide a couple relevant sales figures to the user in a quick lookup flow for assistance.

On print preview page:
1. Add a small info 'i' or '?' icon next to Expected Sales field. Clicking on the icon will display a small pop-up/tooltip with the relevant information below the expected sales field. If the icon seems unnecessary, perhaps the tooltip can just auto-display when user clicks on the field.
2. We want to display only two figures for now:
a. Todays sales:  This is the number entered in the 'Home' -> 'Todays Sales' field.
b. Previous weeks sales for the day:  The expected sales figure is for the next day. So if the next day is Thursday for example, we want to get the 'Today sales' (i.e. the actual sales figure) from last week Thursday and display it. Restaurant sales tend to follow a pattern and the weekday is significant.

**Comment by swash99** [comment]
Sales information display added in commit d3a1401
