### ISSUE TITLE
Change username font in displayed message

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#18]
Usernames in the message conversation are in the same font as the message and can be hard to differentiate from the message. Perhaps make the username bold?
The username should be replaced with the user first/last name when those columns are added to the database.

**Comment by swash99** [comment]
The font has been set to bold and the color changed so its more visible and easier to differentiate. 

The username has been replaced with a users first name and last name. The first and last names appear in both conversations and messages. FIxed #29
