### ISSUE TITLE
Create an internal messaging system

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#2]
The general flow of using an inventory system requires the information displayed by the 'print preview' table to be passed to other people in the company as the next step. Currently this is done by copy/pasting the table into an email and sending it to the next person -- definitely not a very clean solution.

The initial step is to create an internal messaging system where the print preview table can be sent to another user in the IMS system. This can later be expanded upon to add more functionality e.g. checking off items which are completed.

**Comment by swash99** [comment]
I think we can close this for now since a general messaging system has been added and is working. Bugs have been highlighted in seperate issues to be resolved later.
