### ISSUE TITLE
Improve print preview table colors

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#20]
Currently grey/white colors are alternately being used for a row background color. At first glance this makes things a bit confusing. Suggest we use grey for the columns titles (Item, Unit, Quantity Present etc) and leave the other row white? Think about it.

**Comment by swash99** [comment]
Changed the colors for the table and the site in general. The table is easier to read now with different colors for column headings (items, unit etc), main category headings (Drinks, Freezer etc) and each data row.
