### ISSUE TITLE
Messages/Conversations table improvements

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#21]
I have a bunch of suggestions to improve the two new tables Messages and Conversations:
- Change name to Message and Conversation. That is the general convention being followed and the idea is that the name refers to what is stored in each row.
- For columns referring to other tables e.g. 'sender' and 'receiver', make them foreign keys (read up on foreign keys and how you can add them via MySQL workbench and phpMyAdmin on the site). This is to ensure that your data relations don't get broken and if for example a user gets deleted, you can add appropriate cascading actions (like delete messages if the user gets deleted? -- not suggesting this is a good idea, but you get what I'm trying to say).
- 'time' should be changed to 'timestamp' in Messages table. Also, change the timestamp column type to that of datetime or timestamp instead of using varchar.

**Comment by swash99** [comment]
1. Names have been changed to Conversation and Message respectively.
2. Added foreign keys on Conversation and Message tables.
   - On updating a user name, foreign keys on 'sender' and 'receiver' ensure that the corresponding names in Conversation and Message tables are also updated.
3. Remaned column 'time' to 'timestamp' in Message table. Its type is now datetime.
