### ISSUE TITLE
Add documentation to php functions

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#22]
PHP functions, especially the ones handling backend SQL queries, should be properly documented to clearly state the purpose of the function, the accepted parameters and the return value.

phpDocumentor seems to be one of the most widely used tools for auto-generation of PHP code doc so I suggest we use that documentation format:    http://www.phpdoc.org/

Sample of phpDoc format:
http://www.phpdoc.org/docs/latest/getting-started/your-first-set-of-documentation.html

This should be implemented after or in parallel with issue #38

**Comment by sa31fh** [comment]
Suggest this be done sooner than later. No one likes tackling documentation and the longer this is delayed the more undocumented PHP code will accumulate.

**Comment by sa31fh** [comment]
Moving this to Phase 2. I have plans for PHP code overhaul so documentation should be handled when that is implemented.

**Comment by sa31fh** [comment]
Since this issue is being pushed back a lot, I'm going to break this up into more consumable sub-tasks and use this issue as the main tracker in the backlog. This issue should be closed once all PHP documentation is complete via sub-tasks.

**Comment by sa31fh** [comment]
Close issue when all sub-tasks have been completed.

**Comment by swash99** [comment]
All sub-tasks have been completed and issues closed
