### ISSUE TITLE
Add new message counter display

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#23]
Display number of unread conversations next to the Messages button in the top bar. Maybe like so for one new conversation: Message (1)

Since you have the concept of a 'conversation', I'm thinking its sufficient to count unread conversations instead of unread messages which might get confusing -- give it some thought.

Suggest the conversation table gets an "unread" column of type TINYINT (http://dev.mysql.com/doc/refman/5.7/en/other-vendor-data-types.html). TINYINT is the smallest type and closest to use as a boolean.

**Comment by swash99** [comment]
A counter has been aded to the "Inbox" tab. Jquery is used to updated the count as a user interacts with the conversations. Some styles were also added to highlight unread conversations.
