### ISSUE TITLE
Move expected sales to somewhere else?

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#25]
The expected sales field  on category_status.php is used to predict the quantity of items necessary for the next day which are displayed in the 'print preview' table. Previously the 'Print Preview' button was relevantly placed right beneath the expected sales field. However now since the print preview button has been moved to the top right corner, the expected sales field seems a little strange and out of place under the categories table. Suggest it be moved to a better place -- I'm not quite certain where that would be, perhaps somewhere in the top bar. Creating this issue so this minor 'problem' can be tackled and kept at the back of mind when designing the interface.

**Comment by swash99** [comment]
Expected Sales has been moved to print_preview.php
