### ISSUE TITLE
New messages in a deleted conversation should appear in Inbox

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#26]
If a user deletes a conversation and receives more messages in that same conversation, that conversation should be moved to Inbox. Given the nature of the messaging system you have essentially created an equivalent of an internal emailing system, so the intuitive behavior for it should be how a service like Gmail would behave.

**Comment by swash99** [comment]
On receiving new messages in a deleted conversation, the conversation status is changed to 'unread' and is moved back to the inbox. A ConversationStatus table was made to store all possible statuses.
