### ISSUE TITLE
Paginate items table

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#31]
In Admin Tasks -> Items, all existing items will be dumped into one table. What happens if your system has 1500 items? The items table should be paginated and only 10 (customizable?) items should be displayed at a time, with  < > buttons to move to other pages. Note that since the Add New Item field is under the table, this can be a significant issue.

Examples:
http://tablesorter.com/docs/example-pager.html
http://en.newinstance.it/2006/09/27/client-side-html-table-pagination-with-javascript/

Putting in backlog for now.

**Comment by swash99** [comment]
Added pagination to the items table in commit 801bf93
