### ISSUE TITLE
All delete buttons should trigger confirmation pop-up

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#33]
A number of tables have a 'Delete' button at the end of the field in Admin Tasks page:
Categories, Items, Users

Its very easy to accidentally click Delete and cause a mess. Clicking delete should trigger a pop-up asking for confirmation for the action to avoid such problems.

**Comment by swash99** [comment]
A simple confirmation has been added using the built-in javascript confirm() function. This implementation can be considered a bit crude. Browsers allow for such dialog boxes to be prevented from opening on a users request and this can break the process of the confirmations. Leaving this issue open to find a better solution.

**Comment by swash99** [comment]
That was a mistake

**Comment by swash99** [comment]
Fixed issue in commit  12cc190
