### ISSUE TITLE
Version 1.0.0: End tasks for phase completion

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#35]
When all the other issues aimed for Version 1.0.0 are completed, the following tasks have to be completed to wrap things up:

**\* Read this wiki:  https://github.com/sa31fh/ims/wiki/Software-Release-Process-Guidelines ***
1. First make a local temporary copy of your files and push all local changes to GitHub so no work is lost.
2. Perform a rebase of Overhaul onto master branch (read the full link including last section of 'Rebase vs Merge'):  https://git-scm.com/book/en/v2/Git-Branching-Rebasing
3. Verify that rebase was successful by switching to master and checking code is up to date and your commit history contains the changes you made on Overhaul.
4. Delete Overhaul and dev branches. 'dev' is no longer needed since we will just create a branch for each phase from now on.
5. Add an annotated 'v1.0.0' tag to master at this point: https://git-scm.com/book/en/v2/Git-Basics-Tagging
6. Push all changes to GitHub and verify that changes were pushed successfully.
7. Send a pull request to me so I can pull your fork changes back into my ims repository.
8. Update site with latest changes.

We will try to take an Agile approach after Version 1.0.0 completion:
- A separate branch created for the phase.
- A more focused number of issues to be addressed in each phase.
- Fewer issues tackled in each phase. We want smaller, faster and more iterations of development.

Related software development methodologies read-up:
https://en.wikipedia.org/wiki/Software_development_process
https://en.wikipedia.org/wiki/Agile_software_development

Focus on waterfall, iterative and incremental, agile approaches.

**Comment by swash99** [comment]
The master branch was successfully merged with overhaul branch. Overhaul and dev branches have been deleted. The tag v1.0.0 was added to the latest commit on master branch. Pull request has been made.
