### ISSUE TITLE
Create wiki for coding style guide

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#36]
A wiki should be created in sa31fh/ims repository GitHub page as a coding style guide for:
- HTML
- Javascript
- PHP
- PHP documentation
- AJAX (if needed)

The aim will be to put in writing things like:
- variable/class/file naming conventions for different scenarios
- indentation style and requirements
- documentation style
- some best practices
- if style guides defined elsewhere are being used, then relevant links to those sources should be provided

The basic wiki should be completed within the scope of this issue, but it is expected to be continually updated as you keep developing and the codebase keeps changing. It will be a reference guide for you as well as anyone else who may work on this project in the future.

Some examples of what kind of things are addressed in a style guide and how:
https://google.github.io/styleguide/cppguide.html
https://google.github.io/styleguide/pyguide.html
https://github.com/google/styleguide
https://www.python.org/dev/peps/pep-0008/

Your wiki is not expected to be as detailed as the links above, but they are meant as an example.

Its a good idea to simply adopt popular and well documented coding style guides like Google. Then you can simply link to them and things are clean and clear:
https://google.github.io/styleguide/javascriptguide.xml
http://google.github.io/styleguide/htmlcssguide.xml

**Comment by sa31fh** [comment]
Since this issue is being pushed back frequently, I'm going to break this up into sub-tasks and make this the main tracker issue in the backlog. This issue should be closed once the basic wiki has been completed. Wiki to be kept up-to-date on a rolling basis in the future as needed.

**Comment by swash99** [comment]
wiki page for coding style guide has been made
