### ISSUE TITLE
Revamp PHP error handling

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#37]
Currently error handling in our PHP code is quite primitive with error messages being echo'ed to the browser and simple boolean return values. Significant improvements can be made in this area by use of PHP exceptions to handle both the type of error and any error messages intended to be communicated.

This has been detailed a little in the wiki "Design: Database Interfacing PHP"

**Comment by swash99** [comment]
The error handling revamp was completed in commit f3bcb8b. 

Any further improvements needed can be handled in future issues.
