### ISSUE TITLE
Revamp PHP database handling code

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#38]
The PHP code used to perform database queries is currently quite simplistic with a lot of functions thrown in a file. This can be made significantly better and more logical by splitting the code into multiple classes depending on the tables being queried and pulling the code out into its own sub-folder.

Wiki:  "Design: Database Interfacing PHP"

**Comment by sa31fh** [comment]
The "Design: Database Interfacing PHP" should give an overview of the expected implementation.

**Comment by swash99** [comment]
The database has been redisgned and tested.
