### ISSUE TITLE
Add Recipe feature

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#42]
A feature to be added under Admin Tasks. A tab to create recipes and associated inventory "items" and quantity of each item to the recipe. The basic idea is to add/provide some functionality by way of which a menu item sold to the customer will automatically subtract the specified item quantities under the recipe section from the inventory. This would automate inventory updates to a large degree.

A big issue with this is trying to interface with the restaurants point of sale system. However, on our end at least, we can at the very least provide an API would can be called to perform inventory updates in the database. For the scope of this feature, just the implementation of recipe addition is sufficient.

**Comment by swash99** [comment]
Initial recipe feature has been added in commit  c68f155
