### ISSUE TITLE
Expected sales box pushed down by items list

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#47]
On category_status.php page, clicking on a category displays the table with associated items. However as the list of items get bigger ("Paper Products" has 45 items right now) it starts to push the Expected Sales input box down the page as well.

**Comment by swash99** [comment]
I think this issue is linked with Issue #25. Since we want to move the expected sales to a better location it should resolve this issue as well.

**Comment by swash99** [comment]
Expected Sales has been moved to print_preview.php
