### ISSUE TITLE
Deleted 'all' conversation selection incorrectly displays one selection

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#48]
In deleted conversations page, selecting 'all' conversations will show 1 item selected even if list is empty. See attached screenshot. It also says "1 item select" instead of "selected"!

![screenshot](https://cloud.githubusercontent.com/assets/182206/13374854/4377a338-dd5e-11e5-9efe-55002fb2b007.jpg)

**Comment by swash99** [comment]
Bug has been fixed in commit 3d4996a
