### ISSUE TITLE
Add ability to differentiate conversation options row

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#49]
I really like the top bar in the messages pages which allows you to select all message,  mark read/unread etc. However there isn't sufficient differentiation in that bar from the expected message list below and at first glance it seems like a bug like a seemingly 'empty' message is being displayed (especially if there are no messages then you only see the checkbox).

Some minor visual improvement (like the top row having a different color may be?) to help set the options bar apart from the messages would make this feature perfect!

**Comment by swash99** [comment]
Issue has been resolved in commit fca50cc
