### ISSUE TITLE
Move add new item/user boxes

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#51]
In Admin Tasks, the add new item/user boxes are below the items/users tables on the respective pages. I think a better position would be for the 'add' fields to be above the item/user list table. Perhaps make the add box collapsible/expandable since people won't need to use them all the time?

Example:
http://wet-boew.github.io/wet-boew-legacy/v3.0/demos/details/details-en.html

**Comment by sa31fh** [comment]
The collapsible 'Add New Items' box looks excellent. Please do the same for 'Add New User' as well.

**Comment by swash99** [comment]
'Add Item' section has been moved into a new sliding drawer located on the top of the page. commit a6a2e59

'Add User' section has been moved into a new sliding drawer located on the top of the page. commit f0b4ff3
