### ISSUE TITLE
Messaging in a deleted conversation does not move the conversation to inbox

### ISSUE THREAD

**Issue by swash99** [swash99/ims#55]
If a message is sent in a deleted conversation, the conversation remains in the deleted session with its status still set as 'deleted' for that user(the sender of the message). The other user in the conversation(the receiver of the message) however, will see it in their inbox even if it was deleted on their end.

Possible solutions are to either move the deleted conversation back into the inbox on sending a message or remove the ability to send a message in a deleted conversation.

**Comment by sa31fh** [comment]
This sounds like a "its a feature not a bug" situation!

I think of the messaging system exactly like I would use my email account:
- The sender can send messages in a deleted email and on the receiving end the conversation gets moved to Inbox even if receiver had it deleted before. This is important on the receiving end so the receiver does not miss a message. 
- My opinion is that the senders conversation should remain in deleted state until it receives a reply from the other side. Then it should be moved to inbox.

Suggest we keep the current implementation i.e. "you use our messaging system just like you use Gmail".

**Comment by sa31fh** [comment]
Take a look at this again with the current status of the messaging functionality. My suggestion is still that the messaging system should behave as close to email/gmail as possible. Close issue if no change is needed.

**Comment by swash99** [comment]
Leaving everything as it is for now. Deleted messages remain in the 'deleted' section unless they receive a reply.
