### ISSUE TITLE
Send message to multiple users

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#59]
The user only has the option of sending a message to one recipient. The option to send message to multiple recipients will add an extra polish. 

This is a very low priority enhancement and a nice-to-have.

**Comment by swash99** [comment]
Would this be like a group chat or just sending the same message in individual conversations.

**Comment by sa31fh** [comment]
Ideally this should follow email style, where its a 'Reply to all' with a potential 'Reply only to sender' option. So yes, like a group chat with an option to make it an individual conversation.

Note that this is a very low priority issue for now and it will likely require some effort. It can be pushed to future if you don't want to tackle it right now.

**Comment by swash99** [comment]
Issue was resolved in commit 8f08e2b
