### ISSUE TITLE
Add customization option for order of items/categories

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#60]
Categories and items are always displayed in alphabetical order. This can be a problem when user is going through their physical inventory and filling in quantities for a lot of items (constant scrolling up and down to find item).

Ideally the user should have the option customizing the order of the categories and items. I suggest the best location to do this would be in **Admin Tasks -> Categories** where the user can move the categories/items order up and down. Bonus points if this can be made drag and drop.

This would also limit the order customization option to admins, which I think is the best approach.

**Comment by swash99** [comment]
Added order customization feature in commit b3ab468
