### ISSUE TITLE
Add quantity along with new item

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#62]
**Admin Tasks -> Items**

When a new item is added, only the item name is unit can be specified. The user will have to go find the item after adding it and then enter its quantity in 'Quantity for Sales ($)' column.

Add field in the 'Add New Item' form so the user can specify the quantity at the same time and saving some time. This field should be optional and a null value should be acceptable.

**Comment by swash99** [comment]
An input field for quantity has been added and it is optional to use. commit a6a2e59
