### ISSUE TITLE
Opening a conversation should scroll down to the last message

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#63]
Opening a new conversation will always display the first message. However for a long conversation it can be frustrating to keep going to the bottom where the most recent message would be.

Add ability to auto-scroll to the last message when a conversation is opened. If you want to be flashy, consider going Gmail style where the older emails in a conversation are collapsed and only the most recent one is displayed.

**Comment by swash99** [comment]
Conversation now scrolls to the latest message when opened. commit  987d46d
