### ISSUE TITLE
Add timeslots for inventory entry and display

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#64]
Background: 
A restaurant has varying customer traffic during a normal day. Few people when it opens at 11 AM, lots of people at lunch and dinner, etc. The inventory system is used in an extended way to not only determine the quantity of item needed, but also **when** it is needed during the day. Currently the manual method used is to determine quantity present, quantity required for the next day and then creating multiple tables of required items and filling out quantity required for morning/evening.

This is a major feature and apparently the inventory system cannot be properly used until this is implemented and working. However it needs some thought as to how it will be implemented properly. In the meantime, perhaps the notes section can be used as a temporary solution to communicate required items. 

The initial solution which comes to mind:
- Perhaps we need to create a timeslots section under Admin Tasks.
- Selecting a timeslot will display the full table of items.
- A 'factor' can be added for each item row. The quantity required will be multiplied by this factor to obtain the quantity for that timeslot.
- If no factor is specified, the quantity required is just split evenly across the timeslots.

**Comment by swash99** [comment]
Are these time slots meant to be fixed like "Morning/Evening/Lunch" etc or should they be flexible slots where the user chooses and creates their own preferred time slots. Either by name or maybe by time ranges.

**Comment by swash99** [comment]
Added timeslots feature in commit 7da3fde
