### ISSUE TITLE
Calculated quantity required is incorrect

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#65]
The algorithm for determining quantity required in the print preview is quite simple:
quantity_required = (base_quantity / base_sales) \* expected_sales - quanty_present

However the quantity required calculation is currently broken. I believe it is due to int type being used instead of float in PHP.  (int) 1.5 will give you 1, the decimal portion will be truncated. 

At first glance, the bug should be fixed by changing the cast to float in the following two places:
- **print_preview.php, line 63:**   (int)$row["quantity"] 
- **base_quantity_table.php, line 11:**   return (int) $result->fetch_assoc()['quantity']; 

The existence of this bug is likely because only integers were being used originally and the quantity conversion to decimal numbers was made later.

Reference:
- http://php.net/manual/en/language.types.php
- http://php.net/manual/en/language.types.integer.php
- http://php.net/manual/en/language.types.float.php
- Type Casting section: http://php.net/manual/en/language.types.type-juggling.php

**Comment by swash99** [comment]
The type casting was indeed the issue. Removing them outputted the correct values.

**Comment by swash99** [comment]
Issue resolved in commit f836614
