### ISSUE TITLE
Version 1.2.0: Finishing tasks

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#66]
- Update version number on site to v1.2.0
- Push all changes and backup
- Rebase b1.2.0 to master
- Add v1.2.0 annotated tag to repo and add a small summary of the changes made. No need to make it very detailed, but if someone is going through release tag history it will give an idea of what was changed.
- Push tag
- Verify rebasing and tagging was successful then delete b1.2.0 branch
- Update auntys site

**Comment by swash99** [comment]
- [x] site version updated to v1.2.0
- [x] rebased with master and pushed all changes
- [x] added tag with summary and pushed tag
- [x] b1.2.0 deleted
- [x] b1.3.0 created
- [x] updated both auntys site and test site
