### ISSUE TITLE
User role cannot be changed

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#8]
In manage_users.php, the 'Role' column has drop down menus with the current role of each user displayed. Right now the role is displayed but no other role is displayed but it cannot be changed since no other role exists in the drop down. The idea is that another role can be chosen for a user and it is auto-assigned. This worked previously.

Also, the currently logged in admin should have that drop down menu disabled (it still shows 'admin'). The idea is that an admin should not be able to change his own role. This guarantees that there will always be at least one admin existing in the system.

**Comment by swash99** [comment]
"Role" columns now display each users role as the selected option, the session admin role column gets disabled and changing the role for a user saves it as their role in the database. Test locally.
