### ISSUE TITLE
Add 'export pdf' option for print preview

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#84]
A bit of a 'problem' remains that there is no way to externally (i.e. outside ims system) get a list of the print preview tables. A request made in this context was to see if an 'export pdf' button could be provided on the print preview page. Clicking on it would dump the print preview table into one pdf file and have it download in the users browser. Not sure what exactly would be required for pdf generation on the server end so some research would need to be done here.

An alternative is to provide a 'send email' feature to mail the print preview table to a given email address. Ideally we would like to avoid this since it will require externally dependencies and setup of an email account which would be used to send these emails.

**Comment by swash99** [comment]
Feature added in commit  3cec846
