### ISSUE TITLE
Improve scrollbar display when browser is resized

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#85]
This is a minor issue and just a nice to have.

When the browser window is resized, the div (? i assume its a div...) containing the table data (e.g. Admin Tasks -> Items) will also resize. After a certain point the div will not become any smaller and will just show vertical and horizontal scrollbars. Now a small issue is that if you resize the browser window to a small size, the div's scrollbars disappear from view and you have to scroll around to find them.

If you look at the attached screenshots:
Screenshot-1:  You see the browser vertical scrollbar and the table divs vertical/horizontal scrollbars.
Screenshot-2:  With the smaller vertical browser window, the divs horizontal scrollbar goes out of view.

Now this is a very very minor issue and the request is to play around with how the website behaves upon browser window resizing and to see if there is a good way to handle it i.e. keep the divs scrollbars always in view so it doesn't confused the user.

![screenshot-1](https://cloud.githubusercontent.com/assets/182206/15094675/1dc68674-147a-11e6-8ee4-505e9c46620b.png)
![screenshot-2](https://cloud.githubusercontent.com/assets/182206/15094676/1dc73b5a-147a-11e6-95bf-752b7f7489fa.png)

**Comment by swash99** [comment]
This issue has been somewhat resolved with improvements to the nav bar in commit 6e4f0b6

Further improvements will be made to make the site as responsive as possible
