### ISSUE TITLE
Use mathematical expression to calculate timeslot quantity

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#86]
Currently we are using the concept of a 'Quantity Factor' for each timeslot.

To enhance the concept, another advanced approach to let the user enter a mathematical expression in the 'Quantity Factor' column (it will likely have to be renamed since it won't be a simple factor any more!) and that expression is used to calculate the quantity required for the timeslot.

Example:
Mathematical expression string in timeslot (x is the quantity required for full day):   "x / 2" 

In PHP:
    `//Using this as an example, in the code we will be using the calculated full day quantity`
    `$full_quantity = 100;`
    `$expression = str_replace('x', $full_quantity, 'x / 2');`
    `$quantity_required = eval('return $expression;');`

The above code is just an example to demonstrate how this could potentially be implemented. There are probably better ways to implement this.

**Comment by swash99** [comment]
Issue resolved in commit bf65a50
