### ISSUE TITLE
Add categories in Items table

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#87]
Admin Tasks -> Items

When the Items list becomes very large, it can be difficult to navigate through it and find what you want (although the alphabetical order does help a lot). A suggestion is to:
- display the items in categories in the admin tasks Items table as well. 
- Make the category collapsible/expandable. 
- Use an 'Uncategorized' category name for uncategorized items.

**Comment by swash99** [comment]
Issue resolved in commit  bf65a50
