### ISSUE TITLE
Display date clearly where relevant

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#88]
In practical use, a careless employee might start adding inventory details under the wrong date (has already happened...). We want to make sure the date is clearly visible in relevant places to avoid this problem as much as possible.

Some related changes which can be made:
- Currently on Home page, if the items list for a category is large, the whole page has to be scrolled down. If the items inventory input div can be made to be vertically scrollable then the dates will always be clearly visible to the user.
- It seems the 'Print Preview' page does not display the date anywhere. A possible solution is to add the date along with the 'Quantity Present' heading (i.e. 'todays' date) and the 'Quantity Required' heading (i.e. 'tomorrows' date). That way it will be very clear which date the data corresponds to.

**Comment by swash99** [comment]
Issue resolved in commit  b55dffd
