### ISSUE TITLE
Add a final 'review' step for inventory entry process

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#89]
A nice to have feature will be to have a 'review' or 'verify' feature. For large inventories, it can be hard to find which items were missed.

I have a few possible solutions in mind:
1. Add a 'Review' button. The user will hit the button once they are done entering the inventory data. The review process will go through the list and make sure nothing was missed. User will be informed of missing items and ideally another table will list only the missing items with the quantity entry fields.
2. Similar to the 'All/Required' toggle button in the print preview page, add an equivalent button on 'Home' page so it toggles button all items in a category or only the items which have not been filled in.
3. Perhaps a marker (like a colored dot?) or a colored highlight (red/green?) of the category name or item entry indicator ('4/45' thingy) can be used on the Home page to indicate which categories are missing things.

Personally I think a combination of solutions 2 and 3 would be the best approach. Solution 1 would be good if more complex steps want to be added in the 'review' process in the future. Something to play around with and investigate to see what makes most sense.

**Comment by swash99** [comment]
Issue resolved in commit    af81dfd
