### ISSUE TITLE
Create flexible option for rounding quantity required

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#92]
A frequent request is changing the rounding functionality of quantity required values. There are a number of problems on the customer end:
- Some quantities require rounding and some do not
- The rounding requirements are different for different items depending on the unit. For example, a 'box' of something might need to be rounded to the nearest whole number. Some items need to be rounded to nearest 0.5. Some items need to be rounded to factors of 8 e.g. a calculated quantity required of 30 would be rounded to 32 (as a multiple of 8)
- Some quantities are rounded up and some are rounded down.

I just came up with an idea which could solve this problem. We integrate the following rounding options in the Items table for each item:
- Whether the quantity required should be rounded up or down. If blank, then calculated quantity required will be displayed as is.
- The amount it needs to be rounded to. This will be a floating point number which can essentially accept any value e.g. 0.25, 0.5, 8, 10 etc

I already have an implementation in mind so I'll just detail it here:

x - Calculated quantity required
y - Multiple which the quantity should be rounded to.

To round up - Round up to the next integer e.g. 0.25 or 0.7 becomes 1:
round_up( x / y) \* y
round_up(30 / 8) \* 8 -> 32   // Rounded up 30 to nearest multiple of 8 i.e. 32

To round down - Round down to the previous integer e.g. 1.25 or 1.7 becomes 1:
round_down( x / y) \* y
round_down(30 / 8) \* 8 -> 24  //Rounded down 30 to nearest multiple of 8 i.e. 24

This also works properly if your values are floating points. Try it:
round_up (10.70 / 0.5) \* 0.5 -> 11
round_down (22.42 / 0.25) \* 0.25 -> 22.25

**Comment by swash99** [comment]
Issue resolved in commit  bf65a50
