### ISSUE TITLE
Time out login session after inactivity

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#94]
Admin Tasks -> Account

A feature should be added to logout a user after a period of inactivity. The time out value (in minutes probably) should be added in the Account settings for each user.

Users tend to keep their browser running on their PC/phone/tablet or never clear out their cache resulting in them being perpetually logged in. In some cases of smartphones/tablets this problem is further complicated since 'closing' the browser doesn't necessarily mean the browser was closed and it may still be running in the background. 

The issue this causes is that the date is not refreshed to the current day until the user logs in again. This causes confusion or accidentally filling in inventory for the wrong day by less-than-careful restaurant employees. An auto-logout after a period of inactivity (lets say 60 mins by default?) can solve this problem. This will force the user to login every day when attempting to enter the inventory details and it will default to the current date.

**Comment by swash99** [comment]
Added feature in commit  db0c037
