### ISSUE TITLE
'Drag here' arrow misplaced

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#95]
Admin Tasks -> Categories

When you drag a category name by the delete icon to delete it, the delete zone has a 'drag here' indicator with an arrow before and after it. The second arrows spacing needs to be fixed.

![screenshot](https://cloud.githubusercontent.com/assets/182206/15479905/9be0a594-20f0-11e6-9929-a4a5615c87c0.jpg)

**Comment by swash99** [comment]
Bug fixed in commit  f5fa7d4
