### ISSUE TITLE
Add arrows to collapsible categories in Items List selector

### ISSUE THREAD

**Issue by sa31fh** [swash99/ims#96]
Admin Tasks -> Items -> Click on a timeslot -> Click on 'Item List' button

The 'Item List' shows items which can be added to a timeslot along with their category. The categories are collapsible. Arrow indicators should be added to those categories indicating if they are in collapsed/expanded state (similar to the ones added in the main items table).

**Comment by swash99** [comment]
Issue resolved in commit 87c0557
